### ISSUE TITLE
SAT Trace to Sequence Diagram in 7.40

### ISSUE THREAD

**Issue by uweku** [nomssi/ABAP-to-PlantUML#1]
Dear Jacques,

thanks a lot for the great blog posts and for sharing the SAT -> Sequence diagram extractor. However, I was stuck with the SAT transaction, specifically the Sequence diagram generation. In our system, there is no menu button or toolbar button, indicating a sequence diagram generation. Neither works F8. It looks like SAP has disabled the button, as stated in note. So I reactivated it, please see attached screenshot
![image](https://user-images.githubusercontent.com/4712909/38452670-df0ec594-3a48-11e8-95e4-4975fb4100b8.png)

Regards,

Uwe

**Comment by nomssi** [comment]
Hello Uwe,

Thanks for the feedback.
I checked in Netweaver 7.51: the code is also commented out, but the sequence generation works...

The behavior is controlled by the variant used to create the trace. The sequence generation is only available with a variant **without aggregation**. The DEFAULT variant enables aggregation, so I always use a custom variant for the trace.

Hope this helps,

JNN
![image](https://user-images.githubusercontent.com/18452507/38457665-3195c0a6-3a94-11e8-8000-9a326295e864.png)
![image](https://user-images.githubusercontent.com/18452507/38457680-4c28e506-3a94-11e8-9331-3a464b79612b.png)

**Comment by uweku** [comment]
Dear Jacques,

I also tried this variant, but had some issues triggering the popup which is provided by you. Anyway, the tool works pretty well, so this message is not really an issue. I'll close it.

Thanks a lot again,

Regards,

Uwe
